# Generated by Django 5.0.6 on 2024-08-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_management", "0002_alter_document_file_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_comment",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
