# Generated by Django 5.0.6 on 2024-08-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_management", "0004_document_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
                ("type", models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="document",
            name="document_name",
        ),
        migrations.RemoveField(
            model_name="document",
            name="document_type",
        ),
        migrations.AddField(
            model_name="document",
            name="document_detail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="document_management.documentdetail",
            ),
        ),
    ]
