# Generated by Django 5.0.6 on 2024-08-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "document_management",
            "0005_documentdetail_remove_document_document_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(default="Not Uploaded", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(null=True),
        ),
    ]
