# Generated by Django 5.0.6 on 2024-08-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "document_management",
            "0006_alter_document_status_alter_document_uploaded_at",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project_type", models.CharField(max_length=100, null=True)),
                ("document_type", models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="documentdetail",
            name="document_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="document_management.documenttype",
            ),
        ),
    ]
