# Generated by Django 5.0.6 on 2024-09-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_management", "0007_documenttype_documentdetail_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentdetail",
            name="name",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
