# Generated by Django 5.0.6 on 2024-10-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_management", "0009_alter_documentdetail_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
