# Generated by Django 5.0.6 on 2024-10-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_management", "0011_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="Document",
            new_name="document",
        ),
    ]
