# Generated by Django 5.0.6 on 2024-10-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_management", "0012_rename_document_feedback_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
