# Generated by Django 5.0.6 on 2024-10-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0030_remove_loan_servicer_loan_inspector"),
        ("document_management", "0012_rename_document_feedback_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawDocuments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("doc_name", models.CharField(max_length=100, null=True)),
                ("file_name", models.CharField(max_length=100, null=True)),
                ("file_id", models.CharField(max_length=255, null=True)),
                ("uploaded_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(default="Not Uploaded", max_length=100, null=True),
                ),
                (
                    "draw_tracking",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.drawtracking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
