# Generated by Django 5.0.6 on 2024-10-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_management", "0013_document_summary"),
        ("document_management", "0013_drawdocuments"),
    ]

    operations = []
