# Generated by Django 5.0.6 on 2024-11-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_management", "0015_alter_feedback_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="comment",
            field=models.CharField(max_length=255),
        ),
    ]
