# Generated by Django 5.0.6 on 2024-09-24 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tier", models.CharField(max_length=20)),
                ("subscription_status", models.CharField(max_length=30, null=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("account_creation_date", models.DateTimeField(blank=True, null=True)),
                ("renew_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
