# Generated by Django 5.0.6 on 2024-09-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payments",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="payments",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_status",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="transaction_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
