# Generated by Django 5.0.6 on 2024-10-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_payments", "0003_payments_current_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tier", models.CharField(max_length=20)),
                ("loan_count", models.IntegerField(max_length=20)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
