# Generated by Django 5.0.6 on 2024-10-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_payments", "0005_alter_subscriptionplan_loan_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
