# Generated by Django 5.0.6 on 2024-11-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_payments", "0006_subscriptionplan_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="risk_metrics",
            field=models.BooleanField(default=False),
        ),
    ]
