# Generated by Django 5.0.6 on 2024-07-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0003_rename_loan_id_loandisbursementschedule_loan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loandisbursementschedule",
            name="amount",
        ),
        migrations.AddField(
            model_name="loandisbursementschedule",
            name="date_scheduled",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loandisbursementschedule",
            name="planned_disbursement_amount",
            field=models.DecimalField(decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name="loandisbursementschedule",
            name="requested_disbursement_amount",
            field=models.DecimalField(decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name="loandisbursementschedule",
            name="draw_request",
            field=models.IntegerField(),
        ),
    ]
