# Generated by Django 5.0.6 on 2024-07-17 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0004_remove_loandisbursementschedule_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=50)),
                (
                    "concrete",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "steel",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "interior",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "carpentery",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "doors",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "windows",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "glass",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "tiles",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "carpet",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "painting",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "lift",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "garden",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.loan",
                    ),
                ),
            ],
        ),
    ]
