# Generated by Django 5.0.6 on 2024-07-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0005_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("milestone", models.CharField(max_length=50)),
                (
                    "percentage_completion",
                    models.DecimalField(decimal_places=2, max_digits=30, null=True),
                ),
                ("review_months", models.IntegerField()),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.loan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContingencyStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("review_months", models.IntegerField()),
                (
                    "cost_to_complete",
                    models.DecimalField(decimal_places=2, max_digits=30, null=True),
                ),
                (
                    "total_direct_cost_budget",
                    models.DecimalField(decimal_places=2, max_digits=30, null=True),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.loan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisbursementSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "theoretical",
                    models.DecimalField(decimal_places=2, max_digits=30, null=True),
                ),
                (
                    "actual",
                    models.DecimalField(decimal_places=2, max_digits=30, null=True),
                ),
                ("review_months", models.IntegerField()),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.loan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("review_months", models.IntegerField()),
                (
                    "deviation_from_schedule_weeks",
                    models.DecimalField(decimal_places=2, max_digits=30, null=True),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction.loan",
                    ),
                ),
            ],
        ),
    ]
