# Generated by Django 5.0.6 on 2024-08-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "construction",
            "0009_rename_current_reviesed_budget_budgetmaster_current_revised_budget_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetmaster",
            name="acquisition_loan",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="building_loan",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="current_revised_budget",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="loan_budget",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="mezzanine_loan",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="project_loan",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="remaining_to_fund",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="total_funded",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="total_funded_percentage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
