# Generated by Django 5.0.6 on 2024-08-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0011_alter_budgetmaster_project_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetmaster",
            name="uses_type",
            field=models.CharField(blank=True, null=True),
        ),
    ]
