# Generated by Django 5.0.6 on 2024-08-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0014_project_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "pending"),
                    ("Approved", "approved"),
                    ("Closed", "closed"),
                ],
                max_length=50,
            ),
        ),
    ]
