# Generated by Django 5.0.6 on 2024-09-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0018_rename_total_released_amount_drawrequest_budget_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drawtracking",
            old_name="date_approved",
            new_name="disbursement_date",
        ),
        migrations.RenameField(
            model_name="drawtracking",
            old_name="disbursement_status",
            new_name="draw_status",
        ),
        migrations.RenameField(
            model_name="drawtracking",
            old_name="date_requested",
            new_name="requested_date",
        ),
        migrations.RenameField(
            model_name="drawtracking",
            old_name="planned_disbursement_amount",
            new_name="total_balance_amount",
        ),
        migrations.RenameField(
            model_name="drawtracking",
            old_name="requested_disbursement_amount",
            new_name="total_budget_amount",
        ),
        migrations.RemoveField(
            model_name="drawrequest",
            name="disbursement_status",
        ),
        migrations.RemoveField(
            model_name="drawtracking",
            name="budget_master",
        ),
        migrations.RemoveField(
            model_name="drawtracking",
            name="date_scheduled",
        ),
        migrations.AddField(
            model_name="drawtracking",
            name="loan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction.loan",
            ),
        ),
        migrations.AddField(
            model_name="drawtracking",
            name="total_draw_amount",
            field=models.DecimalField(decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name="drawtracking",
            name="total_funded_amount",
            field=models.DecimalField(decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name="drawtracking",
            name="total_released_amount",
            field=models.DecimalField(decimal_places=3, max_digits=30, null=True),
        ),
    ]
