# Generated by Django 5.0.6 on 2024-09-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "construction",
            "0020_budgetmaster_adjustments_budgetmaster_equity_budget_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="budgetmaster",
            old_name="project_total",
            new_name="original_loan_budget",
        ),
    ]
