# Generated by Django 5.0.6 on 2024-09-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0021_rename_project_total_budgetmaster_original_loan_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetmaster",
            name="current_revised_budget",
        ),
    ]
