# Generated by Django 5.0.6 on 2024-09-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0022_remove_budgetmaster_current_revised_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetmaster",
            name="equity_budget",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
