# Generated by Django 5.0.6 on 2024-09-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0023_alter_budgetmaster_equity_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetmaster",
            name="adjustments",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="original_loan_budget",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="revised_budget",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
