# Generated by Django 5.0.6 on 2024-09-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0024_alter_budgetmaster_adjustments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="enddate",
        ),
        migrations.RemoveField(
            model_name="project",
            name="startdate",
        ),
        migrations.AddField(
            model_name="project",
            name="block",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="city",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="lot",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="state",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="street_address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="zip_Code",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
