# Generated by Django 5.0.6 on 2024-10-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0026_alter_loan_inspector_alter_loan_lender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetmaster",
            name="acquisition_loan",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="building_loan",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="loan_budget",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="mezzanine_loan",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="project_loan",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="remaining_to_fund",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="total_funded",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmaster",
            name="total_funded_percentage",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
