# Generated by Django 5.0.6 on 2024-10-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0027_alter_budgetmaster_acquisition_loan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawtracking",
            name="total_funded_amount",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=30, null=True
            ),
        ),
    ]
