# Generated by Django 5.0.6 on 2024-10-23 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0028_alter_drawtracking_total_funded_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="inspector",
        ),
        migrations.AddField(
            model_name="loan",
            name="servicer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servicer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
