# Generated by Django 5.0.6 on 2024-10-23 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0029_remove_loan_inspector_loan_servicer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="servicer",
        ),
        migrations.AddField(
            model_name="loan",
            name="inspector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspector",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
