# Generated by Django 5.0.6 on 2024-11-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0030_remove_loan_servicer_loan_inspector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loandescription",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="project",
            name="address",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("residential", "Residential"),
                    ("commercial", "Commercial"),
                    ("industrial", "Industrial"),
                    ("hospitality", "Hospitality"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="street_address",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
