# Generated by Django 5.0.6 on 2024-11-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "construction",
            "0031_alter_loan_loandescription_alter_project_address_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UsesMapping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project_type", models.CharField(max_length=200)),
                ("uses_type", models.CharField(max_length=200)),
                ("uses", models.CharField(max_length=200)),
                ("is_locked", models.BooleanField(default=False)),
            ],
        ),
    ]
