# Generated by Django 5.0.6 on 2024-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0032_usesmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawtracking",
            name="title",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
